-- Pokémon Nostalgia: dediche private + visitatori giornalieri anonimi.
-- Incolla tutto nel SQL Editor di Supabase ed esegui una volta.

create table if not exists public.dediche (
  id bigint generated by default as identity primary key,
  nickname text,
  message text not null,
  created_at timestamptz not null default now(),
  approved boolean not null default false,
  constraint dediche_message_length check (char_length(message) between 3 and 360),
  constraint dediche_nickname_length check (char_length(coalesce(nickname, '')) <= 24)
);

alter table public.dediche enable row level security;

drop policy if exists "Inserimento pubblico dediche" on public.dediche;
create policy "Inserimento pubblico dediche"
on public.dediche
for insert
to anon
with check (
  char_length(message) between 3 and 360
  and char_length(coalesce(nickname, '')) <= 24
);

grant insert on table public.dediche to anon;
grant usage, select on sequence public.dediche_id_seq to anon;

create table if not exists public.daily_visitors (
  visit_day date not null default current_date,
  visitor_id text not null,
  created_at timestamptz not null default now(),
  primary key (visit_day, visitor_id),
  constraint daily_visitor_id_length check (char_length(visitor_id) between 20 and 80)
);

alter table public.daily_visitors enable row level security;

create or replace function public.register_daily_visit(p_visitor_id text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  today_count bigint;
begin
  if p_visitor_id is null or char_length(p_visitor_id) < 20 or char_length(p_visitor_id) > 80 then
    raise exception 'visitor id non valido';
  end if;

  insert into public.daily_visitors (visit_day, visitor_id)
  values (current_date, p_visitor_id)
  on conflict (visit_day, visitor_id) do nothing;

  select count(*) into today_count
  from public.daily_visitors
  where visit_day = current_date;

  return today_count;
end;
$$;

revoke all on function public.register_daily_visit(text) from public;
grant execute on function public.register_daily_visit(text) to anon;


create or replace view public.daily_visit_totals as
select visit_day, count(*)::bigint as visitors
from public.daily_visitors
group by visit_day
order by visit_day desc;

revoke all on table public.daily_visit_totals from anon;
